---
# Basic demo of using Ansible to create a virtual machine on Pouta.csc.fi
#
# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#
- name: Create virtual machine on cPouta
  hosts: localhost # The OpenStack modules run on your local machine.
  connection: local

  vars:
    # These will need changing based on your project
    demo_key: lalves
    demo_sg: lalvesSG
    demo_security_groups: default,{{ demo_sg }} # don't add spaces here!

  tasks:
    - name: Create security group
      os_security_group: name={{ demo_sg }}

    - name: Add rule to security group to allow access to jenkins from the internet
      os_security_group_rule:
        security_group: "{{ demo_sg }}"
        protocol: tcp
        port_range_min: 8080
        port_range_max: 8080
        remote_ip_prefix: 0.0.0.0/0

    - name: Add rule to security group to all ssh from current system
      os_security_group_rule:
        security_group: "{{ demo_sg }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: "{{ ansible_default_ipv4.address }}/32"

    - name: Create a virtual machine
      register: result
      os_server:
        name: fgci-cicd
        image: CentOS-7.0
        flavor: tiny
        key_name: "{{ demo_key }}"
        security_groups: "{{ demo_security_groups }}"
        network: "core"

    - name: Create a virtual machine
      register: result
      os_server:
        name: fgci-cicd
        image: CentOS-7.0
        flavor: tiny
        key_name: "{{ demo_key }}"
        security_groups: "{{ demo_security_groups }}"
      until: (result.openstack is defined) and (result.openstack.networks.values()[0] | length > 1)
      delay: 20
      retries: 50 

    - name: Store the auto-allocated floating IP address
      set_fact: floating_ip={{ result.openstack.networks.values()[0][1] }}
    - name: Add new host to inventory
      add_host: name={{ floating_ip }} groups=new
    - name: clear ssh known_hosts
      known_hosts: name={{ floating_ip }} state=absent
      when: result | changed
    - name: Wait for instance to be ready
      wait_for: host={{ floating_ip }} port=22 search_regex=OpenSSH delay=60

- name: Configure demo host
  hosts: new
  remote_user: cloud-user
  become: yes  # sudo to root
  vars:

  tasks:
   - name: Install firewalld
     yum: name=firewalld state=present

   - name: Start firewalld
     service: name=firewalld state=started enabled=yes sleep=10

   - name: Wait for firewalld
     pause: seconds=30

   - name: Configure firewalld for ssh
     firewalld: service=ssh permanent=true state=enabled
     notify:
       - restart firewalld

   - name: Configure firewalld for jenkins server
     firewalld: port=8080/tcp permanent=true state=enabled
     notify:
       - restart firewalld


  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted sleep=5    

- name: Jenkins
  hosts: jenkins
  become: yes
  roles:
    - ansible-jenkins

